/**
 * PhishShield Gmail Add-on
 * MVP
 */

const PHISHSHIELD_API =
  'https://phishshield-app.onrender.com';

const TOKEN_PROPERTY =
  'PHISHSHIELD_GMAIL_TOKEN';


/**
 * Homepage shown when the add-on is opened.
 */
function buildHomeCard() {

  const token =
    PropertiesService
      .getUserProperties()
      .getProperty(TOKEN_PROPERTY);

  if (!token) {
    return buildConnectCard();
  }

  return CardService.newCardBuilder()

    .setHeader(
      CardService.newCardHeader()
        .setTitle('PhishShield')
        .setSubtitle('Phishing Email Protection')
    )

    .addSection(

      CardService.newCardSection()

        .addWidget(
          CardService.newTextParagraph()
            .setText(
              '<b>PhishShield is connected.</b><br>' +
              'Open an email and analyze it directly from Gmail.'
            )
        )

        .addWidget(
          CardService.newTextButton()
            .setText('Disconnect PhishShield')
            .setOnClickAction(
              CardService.newAction()
                .setFunctionName('disconnectPhishShield')
            )
        )
    )

    .build();
}


/**
 * Card shown when a Gmail message is opened.
 */
function buildGmailCard(e) {

  const token =
    PropertiesService
      .getUserProperties()
      .getProperty(TOKEN_PROPERTY);

  if (!token) {
    return buildConnectCard();
  }

  return CardService.newCardBuilder()

    .setHeader(
      CardService.newCardHeader()
        .setTitle('PhishShield')
        .setSubtitle('Email Security Analysis')
    )

    .addSection(

      CardService.newCardSection()

        .addWidget(
          CardService.newTextParagraph()
            .setText(
              '<b>Suspicious email?</b><br>' +
              'Analyze the currently opened email with PhishShield.'
            )
        )

        .addWidget(
          CardService.newTextButton()
            .setText('Analyze with PhishShield')
            .setTextButtonStyle(
              CardService.TextButtonStyle.FILLED
            )
            .setOnClickAction(
              CardService.newAction()
                .setFunctionName('analyzeCurrentEmail')
            )
        )

    )

    .build();
}


/**
 * Display the connection screen.
 */
function buildConnectCard() {

  const tokenInput =
    CardService.newTextInput()
      .setFieldName('connectionToken')
      .setTitle('PhishShield Connection Token')
      .setHint(
        'Paste the token generated by PhishShield'
      );

  const connectButton =
    CardService.newTextButton()
      .setText('Connect PhishShield')
      .setTextButtonStyle(
        CardService.TextButtonStyle.FILLED
      )
      .setOnClickAction(
        CardService.newAction()
          .setFunctionName('saveConnectionToken')
      );

  return CardService.newCardBuilder()

    .setHeader(
      CardService.newCardHeader()
        .setTitle('Connect PhishShield')
        .setSubtitle('Gmail Security Integration')
    )

    .addSection(

      CardService.newCardSection()

        .addWidget(
          CardService.newTextParagraph()
            .setText(
              '<b>Connect your PhishShield account.</b><br><br>' +
              'Generate a Gmail connection token from your ' +
              'PhishShield account and paste it below.'
            )
        )

        .addWidget(tokenInput)

        .addWidget(connectButton)

    )

    .build();
}


/**
 * Save the connection token for this Google account.
 */
function saveConnectionToken(e) {

  try {

    const formInputs =
      e.commonEventObject &&
      e.commonEventObject.formInputs;

    const tokenField =
      formInputs &&
      formInputs.connectionToken;

    const values =
      tokenField &&
      tokenField.stringInputs &&
      tokenField.stringInputs.value;

    const token =
      values && values.length
        ? String(values[0]).trim()
        : '';

    if (!token || token.length < 40) {

      return createErrorCard(
        'Please enter a valid PhishShield connection token.'
      );
    }

    // Test the token before saving it.
    const testResponse =
      UrlFetchApp.fetch(
        PHISHSHIELD_API + '/api/v1/analyze-gmail',
        {
          method: 'post',

          contentType: 'application/json',

          headers: {
            Authorization: 'Bearer ' + token
          },

          payload: JSON.stringify({
            message: {
              subject: '',
              from: '',
              to: '',
              cc: '',
              date: '',
              body: ''
            }
          }),

          muteHttpExceptions: true
        }
      );

    const status =
      testResponse.getResponseCode();

    // 400 means the token was accepted but
    // the test message was empty.
    // 401 means the token is invalid.
    if (status === 401) {

      return createErrorCard(
        'The PhishShield connection token is invalid or revoked.'
      );
    }

    if (status >= 500) {

      return createErrorCard(
        'PhishShield server is currently unavailable.'
      );
    }

    PropertiesService
      .getUserProperties()
      .setProperty(
        TOKEN_PROPERTY,
        token
      );

    return CardService.newCardBuilder()

      .setHeader(
        CardService.newCardHeader()
          .setTitle('PhishShield Connected')
          .setSubtitle('Gmail Security Integration')
      )

      .addSection(

        CardService.newCardSection()

          .addWidget(
            CardService.newTextParagraph()
              .setText(
                '<b>Connection successful.</b><br><br>' +
                'Open a Gmail message and click ' +
                '<b>Analyze with PhishShield</b>.'
              )
          )

      )

      .build();

  } catch (error) {

    console.error(error);

    return createErrorCard(
      'Connection failed: ' +
      error.message
    );
  }
}


/**
 * Disconnect PhishShield from this Google account.
 */
function disconnectPhishShield() {

  try {

    const token =
      PropertiesService
        .getUserProperties()
        .getProperty(TOKEN_PROPERTY);

    if (token) {

      UrlFetchApp.fetch(
        PHISHSHIELD_API +
        '/api/integrations/gmail/revoke',
        {
          method: 'post',

          headers: {
            Authorization: 'Bearer ' + token
          },

          muteHttpExceptions: true
        }
      );
    }

  } catch (error) {

    console.error(
      'Disconnect error:',
      error
    );

  } finally {

    PropertiesService
      .getUserProperties()
      .deleteProperty(
        TOKEN_PROPERTY
      );
  }

  return buildConnectCard();
}


/**
 * Analyze the currently opened Gmail message.
 */
function analyzeCurrentEmail(e) {

  try {

    if (
      !e ||
      !e.gmail ||
      !e.gmail.messageId
    ) {

      return createErrorCard(
        'Unable to access the current Gmail message.'
      );
    }

    const messageId =
      e.gmail.messageId;

    const accessToken =
      e.gmail.accessToken;

    if (!accessToken) {

      return createErrorCard(
        'Gmail did not provide a message access token.'
      );
    }

    GmailApp.setCurrentMessageAccessToken(
      accessToken
    );

    const message =
      GmailApp.getMessageById(
        messageId
      );

    if (!message) {

      return createErrorCard(
        'The current Gmail message could not be found.'
      );
    }

    const payload = {

      provider: 'gmail',

      message: {

        from:
          message.getFrom(),

        to:
          message.getTo(),

        cc:
          message.getCc(),

        subject:
          message.getSubject(),

        date:
          message.getDate().toISOString(),

        body:
          message.getPlainBody()
      }
    };

    return sendToPhishShield(
      payload
    );

  } catch (error) {

    console.error(error);

    return createErrorCard(
      'Analysis failed: ' +
      error.message
    );
  }
}


/**
 * Send the email to PhishShield.
 */
function sendToPhishShield(payload) {

  try {

    const token =
      PropertiesService
        .getUserProperties()
        .getProperty(
          TOKEN_PROPERTY
        );

    if (!token) {

      return buildConnectCard();
    }

    const response =
      UrlFetchApp.fetch(

        PHISHSHIELD_API +
        '/api/v1/analyze-gmail',

        {

          method: 'post',

          contentType:
            'application/json',

          headers: {

            Authorization:
              'Bearer ' + token
          },

          payload:
            JSON.stringify(payload),

          muteHttpExceptions:
            true
        }
      );

    const status =
      response.getResponseCode();

    const text =
      response.getContentText();

    if (status === 401) {

      PropertiesService
        .getUserProperties()
        .deleteProperty(
          TOKEN_PROPERTY
        );

      return createErrorCard(
        'Your PhishShield connection has expired or been revoked. Please reconnect.'
      );
    }

    if (
      status < 200 ||
      status >= 300
    ) {

      console.error(
        'PhishShield API error:',
        status,
        text
      );

      return createErrorCard(
        'PhishShield server returned HTTP ' +
        status
      );
    }

    const result =
      JSON.parse(text);

    return createResultCard(
      result
    );

  } catch (error) {

    console.error(error);

    return createErrorCard(
      'Could not connect to PhishShield: ' +
      error.message
    );
  }
}


/**
 * Display analysis results.
 */
function createResultCard(result) {

  const investigation =
    result.investigation ||
    result;

  const scoring =
    investigation.scoring ||
    {};

  const score =
    scoring.score ?? 0;

  const risk =
    scoring.riskCategory ||
    'UNKNOWN';

  const factors =
    scoring.factors ||
    [];

  let findingsText =
    'No individual findings were returned.';

  if (
    Array.isArray(factors) &&
    factors.length > 0
  ) {

    findingsText =
      factors
        .slice(0, 5)
        .map(function(factor) {

          return (
            '• <b>' +
            escapeHtml(
              factor.title ||
              factor.category ||
              'Finding'
            ) +
            '</b> — ' +
            escapeHtml(
              factor.desc ||
              ''
            ) +
            ' <b>(+' +
            String(
              factor.points || 0
            ) +
            ')</b>'
          );

        })
        .join('<br><br>');
  }


  return CardService.newCardBuilder()

    .setHeader(

      CardService.newCardHeader()

        .setTitle(
          'PhishShield Result'
        )

        .setSubtitle(
          'Email Security Analysis'
        )
    )

    .addSection(

      CardService.newCardSection()

        .addWidget(

          CardService.newTextParagraph()
            .setText(
              '<b>Risk Level</b><br>' +
              '<font size="large">' +
              escapeHtml(risk) +
              '</font>'
            )
        )

        .addWidget(

          CardService.newTextParagraph()
            .setText(
              '<b>Risk Score</b><br>' +
              String(score) +
              ' / 100'
            )
        )

        .addWidget(

          CardService.newTextParagraph()
            .setText(
              '<b>Key Findings</b><br><br>' +
              findingsText
            )
        )

    )

    .addSection(

      CardService.newCardSection()

        .addWidget(

          CardService.newTextButton()

            .setText(
              'View Full Investigation'
            )

            .setOpenLink(

              CardService.newOpenLink()

                .setUrl(
                  PHISHSHIELD_API
                )

                .setOpenAs(
                  CardService.OpenAs.FULL_SIZE
                )

                .setOnClose(
                  CardService.OnClose.NOTHING
                )
            )
        )

    )

    .build();
}


/**
 * Display an error.
 */
function createErrorCard(message) {

  return CardService.newCardBuilder()

    .setHeader(

      CardService.newCardHeader()

        .setTitle(
          'PhishShield'
        )

        .setSubtitle(
          'Analysis Error'
        )
    )

    .addSection(

      CardService.newCardSection()

        .addWidget(

          CardService.newTextParagraph()

            .setText(
              '<b>Something went wrong.</b>' +
              '<br><br>' +
              escapeHtml(message)
            )
        )

    )

    .build();
}


/**
 * Escape HTML before displaying
 * server-generated text inside a card.
 */
function escapeHtml(value) {

  return String(value)

    .replace(
      /&/g,
      '&amp;'
    )

    .replace(
      /</g,
      '&lt;'
    )

    .replace(
      />/g,
      '&gt;'
    )

    .replace(
      /"/g,
      '&quot;'
    )

    .replace(
      /'/g,
      '&#039;'
    );
}